name: Build companion

on:
  pull_request:
    branches: [ master ]
    paths:
    - 'companion/**'

defaults:
  run:
    working-directory: companion

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: ./build.sh
    - name: Test packaging
      run: ./build.sh --package
  build-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: ./build.bat
    - name: Test packaging
      run: ./build.bat --package
